instrumentation:
    root: src/
    preserve-comments: true
    default-excludes: true
    include-all-sources: true
reporting:
    print: summary
    reports:
        - lcov
    dir: ./reports/coverage